# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intent.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cintent.proto\x12\x06intent\"\xe0\x01\n\rIntentContext\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x15\n\rstate_version\x18\x03 \x01(\x05\x12\x10\n\x08trace_id\x18\x04 \x01(\t\x12\x42\n\x0f\x63urrent_failure\x18\x05 \x03(\x0b\x32).intent.IntentContext.CurrentFailureEntry\x1a\x35\n\x13\x43urrentFailureEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb4\x03\n\x0e\x42\x65liefEvidence\x12\x14\n\x0cintent_score\x18\x01 \x01(\x01\x12\x14\n\x0cintent_level\x18\x02 \x01(\t\x12\x1f\n\x17historical_transactions\x18\x03 \x01(\x05\x12\x1f\n\x17successful_transactions\x18\x04 \x01(\x05\x12\x1b\n\x13\x66\x61iled_transactions\x18\x05 \x01(\x05\x12\x19\n\x11\x63heckout_failures\x18\x06 \x01(\x05\x12\x18\n\x10payment_failures\x18\x07 \x01(\x05\x12\x0f\n\x07retries\x18\x08 \x01(\x05\x12\x1e\n\x16\x61uthorization_failures\x18\t \x01(\x05\x12\x18\n\x10\x63\x61pture_failures\x18\n \x01(\x05\x12\x1b\n\x13settlement_failures\x18\x0b \x01(\x05\x12\x16\n\x0ehistory_status\x18\x0c \x01(\t\x12\x12\n\nconfidence\x18\r \x01(\x01\x12\x17\n\x0fraw_event_count\x18\x0e \x01(\x05\x12\x1a\n\x12parsed_event_count\x18\x0f \x01(\x05\x12\x19\n\x11parse_error_count\x18\x10 \x01(\x05\"\xf9\x01\n\x0e\x42\x65liefResponse\x12\x11\n\tbelief_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x15\n\ragent_version\x18\x03 \x01(\t\x12\x16\n\x0etransaction_id\x18\x04 \x01(\t\x12\x15\n\rstate_version\x18\x05 \x01(\x05\x12\x16\n\x0erecommendation\x18\x06 \x01(\t\x12\x12\n\nconfidence\x18\x07 \x01(\x01\x12\x13\n\x0breason_code\x18\x08 \x01(\t\x12\x11\n\ttimestamp\x18\t \x01(\t\x12(\n\x08\x65vidence\x18\n \x01(\x0b\x32\x16.intent.BeliefEvidence2O\n\x12IntentAgentService\x12\x39\n\x08\x45valuate\x12\x15.intent.IntentContext\x1a\x16.intent.BeliefResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INTENTCONTEXT_CURRENTFAILUREENTRY']._options = None
  _globals['_INTENTCONTEXT_CURRENTFAILUREENTRY']._serialized_options = b'8\001'
  _globals['_INTENTCONTEXT']._serialized_start=25
  _globals['_INTENTCONTEXT']._serialized_end=249
  _globals['_INTENTCONTEXT_CURRENTFAILUREENTRY']._serialized_start=196
  _globals['_INTENTCONTEXT_CURRENTFAILUREENTRY']._serialized_end=249
  _globals['_BELIEFEVIDENCE']._serialized_start=252
  _globals['_BELIEFEVIDENCE']._serialized_end=688
  _globals['_BELIEFRESPONSE']._serialized_start=691
  _globals['_BELIEFRESPONSE']._serialized_end=940
  _globals['_INTENTAGENTSERVICE']._serialized_start=942
  _globals['_INTENTAGENTSERVICE']._serialized_end=1021
# @@protoc_insertion_point(module_scope)
